"""Update conversation_history table structure

Revision ID: 443c0714645a
Revises: 3d678c3a2b0e
Create Date: 2024-07-24 20:12:03.259570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '443c0714645a'
down_revision: Union[str, None] = '3d678c3a2b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('user_message', sa.Text(), nullable=True))
    op.add_column('conversation_history', sa.Column('bot_response', sa.Text(), nullable=True))
    op.alter_column('conversation_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('conversation_history', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('conversation_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('conversation_history', 'bot_response')
    op.drop_column('conversation_history', 'user_message')
    # ### end Alembic commands ###
